### ISSUE TITLE
/reddit/post.g.dart not found

### ISSUE THREAD

**Issue by lucasjinreal** [jbarr21/flews#3]
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  /Volumes/xs/awesome/uranus/clients/flutter/vendor/flews/lib/reddit/post.dart
...refers, in an import, to the following library:
  /Volumes/xs/awesome/uranus/clients/flutter/vendor/flews/lib/reddit/post.g.dart
Unfortunately, that library does not appear to exist on your file system.

**Comment by jbarr21** [comment]
you need to generated the models
```
./flutterw packages pub run build_runner build
./flutterw run
```
